### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by nalind**
Bump most of our explicit dependencies for which the bot didn't already open PRs to make that happen.

### CODE REVIEW

**Comment by nalind** [comment]
Seems integration with Travis is broken, and we're not running conformance tests.  I don't have the privileges to examine the settings over there or over here.

**Comment by nalind** [comment]
Travis integration is working again?  Confusing, but I'll take it.

**Comment by rhatdan** [comment]
Needs a rebase.

**Pull request merged**
