### PR TITLE
go modules & c/storage references

### PR DESCRIPTION
**Pull request by vrothberg**
* Migrate to using go modules
* Use containers/storage where possible

Motivated by some build issues in Docker packages: https://github.com/containers/libpod/pull/4598#issuecomment-560304335

### CODE REVIEW

**Comment by vrothberg** [comment]
@smarterclayton @nalind PTAL. The change is not strictly fixing the issue as docker/docker is breaking with newer x/sys versions but I guess this janitorial PR is still worth merging.

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by vrothberg** [comment]
ping, can we merge this?

**Comment by vrothberg** [comment]
ping

**Pull request closed without merging**
