### PR TITLE
Migrate to Go modules

### PR DESCRIPTION
**Pull request by nalind**
Newer versions of Go refuse to build imagebuilder without a go.mod.  So let's migrate from the older vendor.conf to modules with the help of `go mod init`.

### CODE REVIEW

**Comment by nalind** [comment]
Okay, we're down to the differences in which files `vndr` and `go mod vendor` keep, except for `google.golang.org/grpc`.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
Not required for this PR, but it might be nice to have a little blurb somewhere on how to vendor.  I know I reference the blurb at the bottom of the install.md on buildah all the time.

**Pull request merged**
