### PR TITLE
Support HEALTHCHECK --start-period

### PR DESCRIPTION
**Pull request by nalind**
Handle a --start-period argument when parsing HEALTHCHECK instructions.

This PR switches to the v1.2.2 release of the upstream `github.com/fsouza/go-dockerclient` package, and I'm not wedded to that, but we currently don't have a branch of https://github.com/openshift/go-dockerclient.git that includes the field that we could switch to instead.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by smarterclayton** [comment]
If Ben has completed his split, please sync to make sure he can bump and then we can try this again.

**Comment by bparees** [comment]
creating an openshift-4.0 branch of go-dockerclient, updating to v1.2.2 and including the carry patch here:
https://github.com/openshift/go-dockerclient/pull/1

after it merges you can bump to the openshift-4.0 branch of openshift/go-dockerclient.

**Comment by bparees** [comment]
https://github.com/openshift/go-dockerclient/pull/1 has merged, so you can redo this using the openshift-4.0 branch now.

**Comment by nalind** [comment]
Rebased.  `glide` updates other components, but those are not currently in this patch.  If it's preferred that we pull in the other updates, I can change it.

**Comment by bparees** [comment]
>  If it's preferred that we pull in the other updates, I can change it.

that's how it's normally done, personally i don't have a preference but i'm not sure who needs to sign off on this (not me).

**Comment by nalind** [comment]
Okay, added them in as part of an additional patch in the series.

**Comment by rhatdan** [comment]
@bparees @smarterclayton PTAL

**Comment by bparees** [comment]
@rhatdan it lgtm, i think you guys have ownership of this repo now.

**Comment by rhatdan** [comment]
@bparees Ownership yes, deep knowledge no.
/lgtm

**Comment by smarterclayton** [comment]
Oh, stupid thing.

**Pull request merged**
