### PR TITLE
Update dependencies, keep up with API changes

### PR DESCRIPTION
**Pull request by nalind**
* bump github.com/containerd/containerd from v1.7.11 to v1.7.12
* bump github.com/docker/docker from v24.0.7 to v25.0.1
* bump github.com/fsouza/go-dockerclient from v1.9.7 to v1.10.1
* bump github.com/containers/storage from v1.51.0 to v1.52.0
* bump github.com/moby/buildkit from v0.11.4 to v0.12.4

The `github.com/docker/docker/api/types.AuthConfig` type was moved to the `github.com/docker/docker/api/types/registry` package, and the type alias that allowed us to not care has gone, so our declarations for variables of that type need to be updated.

### CODE REVIEW

**Comment by nalind** [comment]
This blocks https://github.com/containers/buildah/pull/5301.  I expect to tag a release once this is merged.

**Comment by mtrmac** [comment]
FWIW, Docker is not using Go modules the usual way, meaning `go github.com/docker/…` does not update transitive dependencies.

The dependencies are managed in a file named `vendor.mod`; I usually copy&paste the whole contents into the `…/docker/docker` caller’s `go.mod`, run `go mod tidy`, and then manually clean up.

Doing so here causes a few more (fairly minor) updates.

**Comment by nalind** [comment]
Oh, I wasn't aware.  Worth doing since there's no automation in this repository for it.

**Comment by TomSweeneyRedHat** [comment]
@nalind tests aren't hip

**Comment by nalind** [comment]
Unit tests are waiting on https://github.com/openshift/release/pull/48288.  I don't have the privileges to see what the errors are in the Go 1.21 build in Travis, but it's passing with 1.20.

**Comment by rhatdan** [comment]
Can we keep it at 1.20 for now?

**Comment by nalind** [comment]
I guess.

**Comment by nalind** [comment]
Unit tests are passing now that https://github.com/openshift/release/pull/48288 is merged, and Travis is only testing with 1.20.
We should probably move off Travis to something where the permissions allow us to view failure logs.

**Pull request merged**
