### PR TITLE
conformance: test non-root USER before WORKDIR

### PR DESCRIPTION
**Pull request by nalind**
Add a test that checks who owns a WORKDIR if it's created after USER sets a non-root default runtime user.  Try to run conformance tests in CI.

### CODE REVIEW

**Comment by giuseppe** [comment]
LGTM

I've opened a similar PR to run the conformance tests using github actions: https://github.com/openshift/imagebuilder/pull/223

From a test run they seem to pass: https://github.com/giuseppe/imagebuilder/actions/runs/2059604397

**Review by giuseppe — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green tests

**Comment by nalind** [comment]
Yeah, we made a change that we didn't test for conformance at the time, and it breaks unless the daemon's using BuildKit (i.e., on the traditional `docker build` path).  Options include backing out that change, or updating the conformance tests to ask for BuildKit.

**Comment by rhatdan** [comment]
I believe the best solution is to move onto BuildKit conformance.  Since this is the direction that Docker is taking.

**Comment by nalind** [comment]
Dumb question time: am I the only person who doesn't see results of the `test` action somewhere in this PR or in this repository?  The bot told me the tests passed about five minutes after I last re-pushed the branch, which is an unusually quick turnaround for the conformance tests.

**Pull request merged**
