### PR TITLE
ADD supports the chown option also

### PR DESCRIPTION
**Pull request by rhatdan**
We need to support the --chown operator for ADD as well as COPY.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@smarterclayton @nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
@bparees PTAL

**Comment by rhatdan** [comment]
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1534505

**Comment by TomSweeneyRedHat** [comment]
Should you add a test similar to https://github.com/openshift/imagebuilder/blob/9e710ba9bcf926e020306b67633bf38b8e671da5/dispatchers_test.go#L38 ?

**Comment by TomSweeneyRedHat** [comment]
FWIW, LGTM too.  Thanks for adding the test.

**Pull request merged**
