### PR TITLE
Add automatic platform args in the global scope

### PR DESCRIPTION
**Pull request by grooverdan**
Based on https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

By default assumed build platform = target platform as builder doesn't [yet?] gave platform.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
In Docker, this is only supported starting with v18.09 while using BuildKit.  The changes here look reasonable to me, @nalind WDYT?

**Comment by rhatdan** [comment]
@mrunalp WDYT?

**Comment by grooverdan** [comment]
Any objections @nalind, @mrunalp ?

**Comment by grooverdan** [comment]
So this is missing some /lgtm and removing the /size/xxl :heart: 
/joike

**Comment by grooverdan** [comment]
:traffic_light:

/joke

**Comment by grooverdan** [comment]
Can you push the vendor github.com/containerd/containerd updates separately? Then I can remove that from the series. That will remove the size/XXL tag enabling this to be merged.

**Comment by TomSweeneyRedHat** [comment]
@nalind @mrunalp @redhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
And scrolling back I realize I never LGTM'd.  So doing so now.
LGTM

**Pull request merged**
