### PR TITLE
Switch to use parsers from github.com/moby/buildkit

### PR DESCRIPTION
**Pull request by rhatdan**
This should give us better handling of multi line labels
and environment variables.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This PR includes a large vendor created by 
dep ensure
To pull in the buildkit bits.

**Comment by smarterclayton** [comment]
Please split the vendor changes into their own commit.  I'll take a look at this soon, although if this is going to cause problems when vendored into origin we need to know that too before we merge.

**Comment by rhatdan** [comment]
Sadly this PR did not solve the issue of multi-line labels when I vendored it into buildah.

**Comment by rhatdan** [comment]
Since this did not actually fix the issue, and the issue I saw failed the same way on Docker, I am closing this.

**Pull request closed without merging**
