### PR TITLE
dockerclient: COPY --from should ignore the source's WORKDIR

### PR DESCRIPTION
**Pull request by nalind**
When COPY is given --from=${stage|image}, the stage's or image's WORKDIR should not be incorporated into the path where we go to look for the source when the source is not specified with an absolute path name.  We previously incorporated the WORKDIR value, but that is not compatible with what `docker build` does.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@flouthoc @umohnani8 @TomSweeneyRedHat @vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by vrothberg** [comment]
LGTM

**Comment by vrothberg** [comment]
I don't think I can merge here.

**Pull request merged**
