### PR TITLE
archiveMapper.Filter: also map hard link target names

### LINKED ISSUE #156: Imagebuilder fails to correctly copy a tarball created in the build stage.
When attempting to build a Presto RHEL image [1] locally, I get the following error:

```bash
--> COPY --from=build /build/presto-server/target/presto-server-${PRESTO_VERSION} ${PRESTO_HOME}
API error (404): Error processing tar file(exit status 1): link /target/presto-server-322.0/lib/animal-sniffer-annotations-1.14.jar /opt/presto/presto-server/plugin/accumulo/animal-sniffer-annotations-1.14.jar: no such file or directory
2020-05-07 16:49:10,179 - atomic_reactor.plugin - ERROR - Build step plugin imagebuilder failed: image build failed (rc=1): API error (404): Error processing tar file(exit status 1): link /target/presto-server-322.0/lib/animal-sniffer-annotations-1.14.jar /opt/presto/presto-server/plugin/accumulo/animal-sniffer-annotations-1.14.jar: no such file or directory
```

For more context, this maven built tarball is curled from brew and unpacked in the build stage. The problem, however, is that both the lib and plugin versions of this animal-sniffer-annotations-1.14 jar appear to be present in the build stage, and furthermore, when re-running using `podman build` instead of the imagebuilder cli, I'm able to successfully build and tag this image without error.

When I re-run with extra log verbosity [2], I get the following:

```bash
I0508 10:38:31.192835  604528 archive.go:43] Transform target/presto-server-322.0/lib/animal-sniffer-annotations-1.14.jar -> /opt/presto/presto-server/lib/animal-sniffer-annotations-1.14.jar: data=false ok=false skip=false err=<nil>
...
I0508 10:38:31.372406  604528 archive.go:43] Transform target/presto-server-322.0/plugin/accumulo/animal-sniffer-annotations-1.14.jar -> /opt/presto/presto-server/plugin/accumulo/animal-sniffer-annotations-1.14.jar: data=false ok=false skip=false err=<nil>
```

[1] https://github.com/kube-reporting/presto/blob/master/Dockerfile.rhel
[2] http://pastebin.test.redhat.com/863281

### PR DESCRIPTION
**Pull request by nalind**
Apply pathname rewriting to the target name field when a header indicates that the entry should be a hard link to another file, which we presumably encountered earlier in the archive.  We would have rewritten that entry's pathname, so this should make our reference to it correct.

Fixes #156.

### CODE REVIEW

**Comment by timflannagan1** [comment]
I played around with these changes locally over the weekend and the image is now able to be built w/o any errors. That said, when deploying Presto using this built image, I'm now getting error around some missing dependencies when attempting to load the presto-accumulo plugin:

```bash
2020-05-11T01:56:51.488Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2020-05-11T01:56:51.489Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle startup complete. System ready.
2020-05-11T01:56:51.494Z	INFO	main	io.prestosql.server.PrestoServer	Working directory: /var/presto/data
2020-05-11T01:56:51.494Z	INFO	main	io.prestosql.server.PrestoServer	Etc directory: /opt/presto/presto-server/etc
2020-05-11T01:56:51.494Z	INFO	main	io.prestosql.server.PluginManager	-- Loading plugin /var/presto/data/plugin/accumulo --
2020-05-11T01:56:51.494Z	INFO	main	io.prestosql.server.PluginManager	Classpath for accumulo:
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/accumulo-core-1.7.4.jar
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/accumulo-fate-1.7.4.jar
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/accumulo-start-1.7.4.jar
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/audience-annotations-0.5.0.redhat-1.jar
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-beanutils-1.7.0.jar
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-codec-1.4.jar
2020-05-11T01:56:51.495Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-collections-3.2.2.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-configuration-1.6.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-digester-1.8.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-io-2.4.0.redhat-1.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-lang-2.4.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-lang3-3.4.0.redhat-003.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-math-2.1.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/commons-vfs2-2.2.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/curator-client-2.12.0.jar
2020-05-11T01:56:51.496Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/curator-framework-2.12.0.jar
2020-05-11T01:56:51.497Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/hadoop-apache-2.7.7-1.jar
2020-05-11T01:56:51.497Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/libthrift-0.9.3-1.jar
2020-05-11T01:56:51.497Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/log4j-1.2.17.redhat-3.jar
2020-05-11T01:56:51.497Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/netty-3.10.6.Final.jar
2020-05-11T01:56:51.497Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/presto-accumulo-322.0.0.redhat-00001.jar
2020-05-11T01:56:51.497Z	INFO	main	io.prestosql.server.PluginManager	    /var/presto/data/plugin/accumulo/zookeeper-3.4.13.redhat-00001.jar
2020-05-11T01:56:51.519Z	INFO	main	io.prestosql.server.PluginManager	Installing io.prestosql.plugin.accumulo.AccumuloPlugin
2020-05-11T01:56:51.520Z	ERROR	main	io.prestosql.server.PrestoServer	com/google/common/collect/ImmutableList
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at io.prestosql.plugin.accumulo.AccumuloPlugin.getConnectorFactories(AccumuloPlugin.java:26)
	at io.prestosql.server.PluginManager.installPlugin(PluginManager.java:182)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:161)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:149)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:130)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:125)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at io.prestosql.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```

As mentioned in the linked issue, when built by Podman and deployed, it works as intended.

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL

**Comment by nalind** [comment]
Ah, we weren't doing _all_ of the processing that we do for `h.Name` to `h.Linkname`.  Added the missing bits.

**Comment by rhatdan** [comment]
@timflannagan1 Please try this out?

**Comment by timflannagan1** [comment]
@rhatdan This is good to go - thanks @nalind.

**Pull request merged**
