### PR TITLE
Bump to Go 1.19

### PR DESCRIPTION
**Pull request by nalind**
Use Go 1.19 instead of 1.16 in go.mod.
Test with 1.19/1.20 in Travis instead of 1.17/1.18. Bump the Travis environment from the default (16.04) to jammy (22.04), which is the latest currently available in Travis.
Update assorted direct dependencies.

Obsoletes #241.

Update conformance tests nonroot-USER-before-WORKDIR-notused and nonroot-USER-before-WORKDIR-used to request that they be built with BuildKit.  Many conformance tests fail if we make this the default; we'll have to make that change and fix those later.

### CODE REVIEW

**Comment by nalind** [comment]
> I will be surprised if this passes without [openshift/release#36040](https://github.com/openshift/release/pull/36040).

Well, I'm surprised.

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
Hmm, updating to docker 23.0.0 apparently doesn't result in API calls getting BuildKit by default after all.  It must be a client default that changed.

**Comment by rhatdan** [comment]
@flouthoc WDYT?

**Comment by flouthoc** [comment]
> Hmm, updating to docker 23.0.0 apparently doesn't result in API calls getting BuildKit by default after all. It must be a client default that changed.

Is this a recent change in docker 23.0.0 ? the PR LGTM. @nalind I think this already includes the needed change which I added here https://github.com/openshift/imagebuilder/pull/246 hence closing #246

**Comment by nalind** [comment]
> > Hmm, updating to docker 23.0.0 apparently doesn't result in API calls getting BuildKit by default after all. It must be a client default that changed.
> 
> Is this a recent change in docker 23.0.0 ?

It's the first item called out in the "New" section in https://docs.docker.com/engine/release-notes/23.0/.

**Comment by rhatdan** [comment]
Since the tests pass is this ready to merge?

**Comment by nalind** [comment]
> Since the tests pass is this ready to merge?

It was testing using a private fork of go-dockerclient to let the client request that the pair of cases that were failing be built using BuildKit instead, and I don't want us depending on my fork.  Now that https://github.com/fsouza/go-dockerclient/pull/961 is merged, we can avoid having to do that.

/retitle Bump to Go 1.19

**Comment by nalind** [comment]
Also if anyone wants to approve https://github.com/openshift/release/pull/36040, it's sure to save us some trouble later.

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
A reminder that this repository has a bot to handle merges.

**Pull request merged**
