### PR TITLE
 issue 87: ensure WORKDIR exists

### PR DESCRIPTION
**Pull request by sosiouxme**
Building on https://github.com/openshift/imagebuilder/pull/50 this PR also ensures that the WORKDIR exists when specified.

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@nalind PTAL

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@smarterclayton had a comment in #50 and that code is included in this PR.  That should be addressed and I'd feel more comfortable holding this one until @nalind gets back.  It LGTM otherwise though.

**Comment by sosiouxme** [comment]
@TomSweeneyRedHat any idea when @nalind gets back?
I needed this fix internally so used this branch to build an RPM... would really like these problems solved in master.

**Comment by TomSweeneyRedHat** [comment]
@nalind is just back and probably still looking through the backlog of emails.  @nalind PTAL

**Comment by sosiouxme** [comment]
thanks!

**Pull request merged**
