### PR TITLE
Bump to v1.2.0

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat PTAL

**Comment by nalind** [comment]
If we're calling this 1.2.0, does the development version start claiming it's 1.3-dev?  Otherwise LGTM.

**Comment by rhatdan** [comment]
We usually only bump the Z access for -dev. rather then the X.  X should only get bumped when there are new features line the chmod stuff.

**Comment by TomSweeneyRedHat** [comment]
Should we be creating a release branch for imagebuilder like we have for the other projects?  The only one we have is an OCP 3.11 one.

**Comment by nalind** [comment]
> We usually only bump the Z access for -dev. rather then the X. X should only get bumped when there are new features line the chmod stuff.

For v1.2.0, X=1, Y=2, Z=0.  The previous release tag was v1.1.8, so this was a bump on Y.

**Comment by rhatdan** [comment]
I miswrote.

We usually only bump the Z access for -dev. rather then the Y. Y should only get bumped when there are new features line the chmod stuff.  

The X Should only be bumped for breaking changes (After 2).

Since we added new functionality we bump the Y.

**Pull request merged**
